CREATE TYPE "SourceType" AS ENUM ('OFFICIAL', 'MEDIA', 'RESEARCH', 'SOCIAL');

ALTER TABLE "Source"
  ALTER COLUMN "url" DROP NOT NULL,
  ADD COLUMN "type" "SourceType" NOT NULL DEFAULT 'OFFICIAL',
  ADD COLUMN "authority" DOUBLE PRECISION NOT NULL DEFAULT 5;
