-- AlterTable
ALTER TABLE "Article" ADD COLUMN     "authority" DOUBLE PRECISION,
ADD COLUMN     "impact" DOUBLE PRECISION,
ADD COLUMN     "novelty" DOUBLE PRECISION,
ADD COLUMN     "reach" DOUBLE PRECISION,
ADD COLUMN     "velocity" DOUBLE PRECISION;
